import GaoLean.GDihedral
import Mathlib.GroupTheory.SemidirectProduct

/-!
# A concrete generalized-dihedral semidirect product

For an additive commutative group `A`, this file constructs the standard
semidirect product

`Multiplicative A ⋊ Multiplicative (ZMod 2)`

in which the nontrivial element of `ZMod 2` acts on `A` by negation. It then
packages the canonical rotations and reflection as `GDihedralData`.
-/

namespace GaoLean.ConcreteGDihedral

variable (A : Type*) [AddCommGroup A]

/-- Negation of `A`, viewed as a multiplicative automorphism. -/
def negMulAut : MulAut (Multiplicative A) :=
  (AddEquiv.neg A).toMultiplicative

@[simp]
theorem negMulAut_apply (a : A) :
    Multiplicative.toAdd (negMulAut A (Multiplicative.ofAdd a)) = -a := rfl

/-- The homomorphism from `ℤ` generated by the negation automorphism. -/
def inversionZHom : ℤ →+ Additive (MulAut (Multiplicative A)) :=
  zmultiplesHom (Additive (MulAut (Multiplicative A)))
    (Additive.ofMul (negMulAut A))

@[simp]
theorem inversionZHom_two : inversionZHom A 2 = 0 := by
  ext a
  change - -Multiplicative.toAdd a = Multiplicative.toAdd a
  simp

/-- The additive `ZMod 2` action, before changing type tags to the
multiplicative acting group required by `SemidirectProduct`. -/
def inversionAddAction : ZMod 2 →+ Additive (MulAut (Multiplicative A)) :=
  ZMod.lift 2 ⟨inversionZHom A, inversionZHom_two A⟩

/-- The nontrivial parity acts by negation. -/
@[simp]
theorem inversionAddAction_one :
    inversionAddAction A 1 = Additive.ofMul (negMulAut A) := by
  unfold inversionAddAction
  rw [show (1 : ZMod 2) = ((1 : ℤ) : ZMod 2) by norm_num]
  rw [ZMod.lift_coe]
  simp [inversionZHom]

/-- The inversion action of `C₂ = Multiplicative (ZMod 2)`. -/
def inversionAction :
    Multiplicative (ZMod 2) →* MulAut (Multiplicative A) :=
  AddMonoidHom.toMultiplicative (inversionAddAction A)

@[simp]
theorem inversionAction_flip (a : A) :
    inversionAction A (Multiplicative.ofAdd 1) (Multiplicative.ofAdd a) =
      Multiplicative.ofAdd (-a) := by
  have h := congrArg
    (fun f : Additive (MulAut (Multiplicative A)) =>
      Multiplicative.toAdd
        ((Additive.toMul f) (Multiplicative.ofAdd a)))
    (inversionAddAction_one A)
  exact h

/-- The concrete generalized-dihedral group of `A`. -/
abbrev Group :=
  SemidirectProduct (Multiplicative A) (Multiplicative (ZMod 2))
    (inversionAction A)

/-- The concrete generalized-dihedral group has twice the cardinality of
its rotation kernel. -/
theorem card_group [Fintype A] :
    Nat.card (Group A) = 2 * Nat.card A := by
  simp [Group, Nat.mul_comm]

/-- Canonical rotations in the concrete semidirect product. -/
def rotation : Multiplicative A →* Group A :=
  SemidirectProduct.inl

/-- The canonical nontrivial reflection `(0, 1)`. -/
def flip : Group A :=
  SemidirectProduct.inr (Multiplicative.ofAdd (1 : ZMod 2))

@[simp]
theorem flip_sq : flip A * flip A = 1 := by
  unfold flip
  rw [← map_mul]
  change SemidirectProduct.inr
      (Multiplicative.ofAdd ((1 : ZMod 2) + 1)) = 1
  have hz : (1 : ZMod 2) + 1 = 0 := by decide
  have h : Multiplicative.ofAdd ((1 : ZMod 2) + 1) = 1 := by
    simpa using congrArg Multiplicative.ofAdd hz
  rw [h, map_one]

@[simp]
theorem flip_mul_rotation (a : A) :
    flip A * rotation A (Multiplicative.ofAdd a) =
      rotation A (Multiplicative.ofAdd (-a)) * flip A := by
  apply SemidirectProduct.ext
  · simp only [SemidirectProduct.mul_left, flip, rotation,
      SemidirectProduct.left_inr, SemidirectProduct.right_inr,
      SemidirectProduct.left_inl, SemidirectProduct.right_inl,
      one_mul]
    simp [inversionAction_flip]
  · rfl

/-- The concrete model satisfies the abstract generalized-dihedral
relations from `GDihedral.lean`. -/
def data : GaoLean.GDihedralData A (Group A) where
  rotation := rotation A
  flip := flip A
  flip_sq := flip_sq A
  flip_mul_rotation := flip_mul_rotation A

@[simp]
theorem data_rot (a : A) :
    (data A).rot a = SemidirectProduct.inl (Multiplicative.ofAdd a) := rfl

@[simp]
theorem data_flip : (data A).flip = flip A := rfl

/-- Concrete pair representation of a reflection `rot a * flip`. -/
@[simp]
theorem data_refl_left (a : A) :
    ((data A).refl a).left = Multiplicative.ofAdd a := by
  simp [GaoLean.GDihedralData.refl, GaoLean.GDihedralData.rot,
    data, rotation, flip]

@[simp]
theorem data_refl_right (a : A) :
    ((data A).refl a).right = Multiplicative.ofAdd (1 : ZMod 2) := by
  simp [GaoLean.GDihedralData.refl, GaoLean.GDihedralData.rot,
    data, rotation, flip]

/-- Full pair representation of the abstract reflection in the concrete
semidirect product. -/
@[simp]
theorem data_refl (a : A) :
    (data A).refl a =
      (⟨Multiplicative.ofAdd a, Multiplicative.ofAdd (1 : ZMod 2)⟩ : Group A) := by
  apply SemidirectProduct.ext
  · exact data_refl_left A a
  · exact data_refl_right A a

end GaoLean.ConcreteGDihedral

#print axioms GaoLean.ConcreteGDihedral.inversionZHom_two
#print axioms GaoLean.ConcreteGDihedral.card_group
#print axioms GaoLean.ConcreteGDihedral.flip_mul_rotation
#print axioms GaoLean.ConcreteGDihedral.data_refl_left
#print axioms GaoLean.ConcreteGDihedral.data_refl_right
#print axioms GaoLean.ConcreteGDihedral.data_refl
