import GaoLean.PGGeneralWeightedArithmetic
import GaoLean.PGDGMCore
import Mathlib.GroupTheory.Archimedean
import Mathlib.GroupTheory.Exponent

/-!
# The gcd--torsion layer for arbitrary integer weights

This file isolates the arithmetic object used in Step 3 of the general
weighted proof.  The weight set remains an arbitrary `Set ℤ`; no finite
enumeration of weights is introduced.
-/

namespace GaoLean

universe u

variable {A : Type u} [AddCommGroup A] [Fintype A]

/-- The subgroup of integers generated by all weight differences and the
ambient exponent. -/
def weightedDifferenceExponentSubgroup
    (W : Set ℤ) (w₀ : ℤ) (A : Type u) [AddCommGroup A] : AddSubgroup ℤ :=
  AddSubgroup.closure
    (((fun w : ℤ => w - w₀) '' W) ∪ {(AddMonoid.exponent A : ℤ)})

/-- A cyclic generator supplied by `Int.subgroup_cyclic`. -/
noncomputable def weightedDifferenceGenerator
    (W : Set ℤ) (w₀ : ℤ) (A : Type u) [AddCommGroup A] : ℤ :=
  (Int.subgroup_cyclic (weightedDifferenceExponentSubgroup W w₀ A)).choose

theorem weightedDifferenceGenerator_spec
    (W : Set ℤ) (w₀ : ℤ) (A : Type u) [AddCommGroup A] :
    weightedDifferenceExponentSubgroup W w₀ A =
      AddSubgroup.closure ({weightedDifferenceGenerator W w₀ A} : Set ℤ) :=
  (Int.subgroup_cyclic (weightedDifferenceExponentSubgroup W w₀ A)).choose_spec

/-- The canonical nonnegative generator of the difference--exponent ideal. -/
noncomputable def weightedDifferenceModulus
    (W : Set ℤ) (w₀ : ℤ) (A : Type u) [AddCommGroup A] : ℕ :=
  Int.natAbs (weightedDifferenceGenerator W w₀ A)

/-- The generated subgroup is exactly `dℤ` for the canonical modulus `d`. -/
theorem weightedDifferenceExponentSubgroup_eq_zmultiples
    (W : Set ℤ) (w₀ : ℤ) (A : Type u) [AddCommGroup A] :
    weightedDifferenceExponentSubgroup W w₀ A =
      AddSubgroup.zmultiples (weightedDifferenceModulus W w₀ A : ℤ) := by
  rw [weightedDifferenceGenerator_spec]
  rw [← AddSubgroup.zmultiples_eq_closure]
  exact (Int.zmultiples_natAbs (weightedDifferenceGenerator W w₀ A)).symm

theorem weight_sub_base_mem_weightedDifferenceExponentSubgroup
    {W : Set ℤ} {w₀ w : ℤ} (hw : w ∈ W)
    (A : Type u) [AddCommGroup A] :
    w - w₀ ∈ weightedDifferenceExponentSubgroup W w₀ A := by
  apply AddSubgroup.subset_closure
  exact Or.inl ⟨w, hw, rfl⟩

theorem exponent_mem_weightedDifferenceExponentSubgroup
    (W : Set ℤ) (w₀ : ℤ) (A : Type u) [AddCommGroup A] :
    (AddMonoid.exponent A : ℤ) ∈ weightedDifferenceExponentSubgroup W w₀ A := by
  apply AddSubgroup.subset_closure
  exact Or.inr (Set.mem_singleton _)

/-- The canonical modulus divides the ambient exponent. -/
theorem weightedDifferenceModulus_dvd_exponent
    (W : Set ℤ) (w₀ : ℤ) (A : Type u) [AddCommGroup A] :
    weightedDifferenceModulus W w₀ A ∣ AddMonoid.exponent A := by
  have hmem := exponent_mem_weightedDifferenceExponentSubgroup W w₀ A
  rw [weightedDifferenceExponentSubgroup_eq_zmultiples] at hmem
  exact Int.natCast_dvd_natCast.mp (Int.mem_zmultiples_iff.mp hmem)

/-- Multiplication by the canonical modulus. -/
noncomputable def weightedDifferenceHom
    (W : Set ℤ) (w₀ : ℤ) (A : Type u) [AddCommGroup A] : A →+ A :=
  nsmulAddMonoidHom (weightedDifferenceModulus W w₀ A)

/-- The `d`-torsion subgroup. -/
noncomputable def weightedDifferenceKernel
    (W : Set ℤ) (w₀ : ℤ) (A : Type u) [AddCommGroup A] : AddSubgroup A :=
  (weightedDifferenceHom W w₀ A).ker

/-- The subgroup of `d`-multiples. -/
noncomputable def weightedDifferenceRange
    (W : Set ℤ) (w₀ : ℤ) (A : Type u) [AddCommGroup A] : AddSubgroup A :=
  (weightedDifferenceHom W w₀ A).range

omit [Fintype A] in
@[simp]
theorem mem_weightedDifferenceKernel_iff
    (W : Set ℤ) (w₀ : ℤ) (x : A) :
    x ∈ weightedDifferenceKernel W w₀ A ↔
      weightedDifferenceModulus W w₀ A • x = 0 := by
  rfl

/-- The kernel of multiplication by `d` is exactly the singleton-value
locus of the weighted block. -/
theorem mem_weightedDifferenceKernel_iff_singletonLocus
    {W : Set ℤ} {w₀ : ℤ} (hw₀ : w₀ ∈ W) (x : A) :
    x ∈ weightedDifferenceKernel W w₀ A ↔
      x ∈ weightedSingletonLocus W := by
  rw [mem_weightedDifferenceKernel_iff]
  constructor
  · intro hdx
    rw [mem_weightedSingletonLocus_iff_smul_eq hw₀]
    intro w hw
    have hmem :=
      weight_sub_base_mem_weightedDifferenceExponentSubgroup
        (W := W) (w₀ := w₀) hw A
    rw [weightedDifferenceExponentSubgroup_eq_zmultiples] at hmem
    obtain ⟨k, hk⟩ := AddSubgroup.mem_zmultiples_iff.mp hmem
    simp only [smul_eq_mul] at hk
    apply sub_eq_zero.mp
    have hdx' : (weightedDifferenceModulus W w₀ A : ℤ) • x = 0 := by
      simpa using hdx
    have hzero : (w - w₀) • x = 0 := by
      rw [← hk, mul_zsmul, hdx', smul_zero]
    rw [sub_zsmul] at hzero
    simpa only [sub_eq_add_neg] using hzero
  · intro hx
    have hall : ∀ z : ℤ,
        z ∈ weightedDifferenceExponentSubgroup W w₀ A → z • x = 0 := by
      intro z hz
      induction hz using AddSubgroup.closure_induction with
      | mem z hz =>
          rcases hz with hz | hz
          · obtain ⟨w, hw, rfl⟩ := hz
            exact hx w hw w₀ hw₀
          · have hz' : z = (AddMonoid.exponent A : ℤ) := by
              simpa only [Set.mem_singleton_iff] using hz
            subst z
            simpa using AddMonoid.exponent_nsmul_eq_zero x
      | zero => simp
      | add a b _ha _hb ha hb => simp [add_zsmul, ha, hb]
      | neg a _ha ha => simp [ha]
    have hdmem : (weightedDifferenceModulus W w₀ A : ℤ) ∈
        weightedDifferenceExponentSubgroup W w₀ A := by
      rw [weightedDifferenceExponentSubgroup_eq_zmultiples]
      exact AddSubgroup.mem_zmultiples _
    simpa using hall _ hdmem

/-- Cardinality-one form of the same kernel characterization. -/
theorem mem_weightedDifferenceKernel_iff_weightedValueBlock_card_eq_one
    {W : Set ℤ} (hW : W.Nonempty) {w₀ : ℤ} (hw₀ : w₀ ∈ W) (x : A) :
    x ∈ weightedDifferenceKernel W w₀ A ↔
      (weightedValueBlock W x).card = 1 := by
  rw [mem_weightedDifferenceKernel_iff_singletonLocus hw₀]
  exact (weightedValueBlock_card_eq_one_iff hW x).symm

/-! ## One-coset control and the first isomorphism theorem -/

/-- Every value in the weighted block lies in the single coset
`w₀ • x + dA`. -/
theorem weightedValueBlock_sub_base_mem_weightedDifferenceRange
    {W : Set ℤ} {w₀ : ℤ} (x y : A)
    (hy : y ∈ weightedValueBlock W x) :
    y - w₀ • x ∈ weightedDifferenceRange W w₀ A := by
  obtain ⟨w, hw, rfl⟩ := (mem_weightedValueBlock_iff W x y).mp hy
  have hmem :=
    weight_sub_base_mem_weightedDifferenceExponentSubgroup
      (W := W) (w₀ := w₀) hw A
  rw [weightedDifferenceExponentSubgroup_eq_zmultiples] at hmem
  obtain ⟨k, hk⟩ := AddSubgroup.mem_zmultiples_iff.mp hmem
  simp only [smul_eq_mul] at hk
  refine ⟨k • x, ?_⟩
  change weightedDifferenceModulus W w₀ A • (k • x) =
    w • x - w₀ • x
  rw [← natCast_zsmul, smul_smul, mul_comm, hk, sub_zsmul]
  simp only [sub_eq_add_neg]

/-- In the quotient by `dA`, a weighted value block is one literal layer. -/
theorem quotientLayer_weightedValueBlock_eq_singleton
    {W : Set ℤ} {w₀ : ℤ} (hw₀ : w₀ ∈ W) (x : A) :
    quotientLayer (weightedDifferenceRange W w₀ A)
        (weightedValueBlock W x) =
      {(w₀ • x : A ⧸ weightedDifferenceRange W w₀ A)} := by
  classical
  ext q
  rw [mem_quotientLayer_iff, Finset.mem_singleton]
  constructor
  · rintro ⟨y, hy, rfl⟩
    exact QuotientAddGroup.eq_iff_sub_mem.mpr
      (weightedValueBlock_sub_base_mem_weightedDifferenceRange x y hy)
  · rintro rfl
    refine ⟨w₀ • x, ?_, rfl⟩
    exact (mem_weightedValueBlock_iff W x (w₀ • x)).2 ⟨w₀, hw₀, rfl⟩

theorem quotientLayer_weightedValueBlock_card_eq_one
    {W : Set ℤ} {w₀ : ℤ} (hw₀ : w₀ ∈ W) (x : A) :
    (quotientLayer (weightedDifferenceRange W w₀ A)
      (weightedValueBlock W x)).card = 1 := by
  classical
  rw [quotientLayer_weightedValueBlock_eq_singleton hw₀]
  simp

/-- First isomorphism theorem for multiplication by `d`. -/
noncomputable def weightedDifferenceQuotientEquivRange
    (W : Set ℤ) (w₀ : ℤ) (A : Type u) [AddCommGroup A] :
    A ⧸ weightedDifferenceKernel W w₀ A ≃+
      weightedDifferenceRange W w₀ A :=
  QuotientAddGroup.quotientKerEquivRange (weightedDifferenceHom W w₀ A)

/-! ## Primitive weights control singleton-layer multiplicity -/

/-- The distinguished weight, restricted to the `d`-torsion subgroup. -/
noncomputable def weightedBaseWeightKernelHom
    (W : Set ℤ) (w₀ : ℤ) (A : Type u) [AddCommGroup A] :
    weightedDifferenceKernel W w₀ A →+ A where
  toFun x := w₀ • (x : A)
  map_zero' := by simp
  map_add' := by intro x y; simp [smul_add]

/-- If the original weights generate `ℤ`, the singleton-layer value
`x ↦ w₀ • x` is injective on the `d`-torsion kernel. -/
theorem weightedBaseWeightKernelHom_injective
    {W : Set ℤ} {w₀ : ℤ} (hw₀ : w₀ ∈ W)
    (hprimitive : IsPrimitiveWeightSet W) :
    Function.Injective (weightedBaseWeightKernelHom W w₀ A) := by
  intro x y hxy
  apply Subtype.ext
  apply sub_eq_zero.mp
  have hxloc : (x : A) ∈ weightedSingletonLocus W :=
    (mem_weightedDifferenceKernel_iff_singletonLocus hw₀ (x : A)).mp x.property
  have hyloc : (y : A) ∈ weightedSingletonLocus W :=
    (mem_weightedDifferenceKernel_iff_singletonLocus hw₀ (y : A)).mp y.property
  have hweighted : ∀ w ∈ W, w • ((x : A) - (y : A)) ∈ (⊥ : AddSubgroup A) := by
    intro w hw
    rw [AddSubgroup.mem_bot]
    rw [smul_sub]
    rw [(mem_weightedSingletonLocus_iff_smul_eq hw₀ (x : A)).mp hxloc w hw]
    rw [(mem_weightedSingletonLocus_iff_smul_eq hw₀ (y : A)).mp hyloc w hw]
    exact sub_eq_zero.mpr hxy
  have hbot : (x : A) - (y : A) ∈ (⊥ : AddSubgroup A) :=
    mem_addSubgroup_of_primitive_weights hprimitive hweighted
  simpa using hbot

/-- Unbundled `Set.InjOn` form of the same multiplicity control. -/
theorem weightedBaseWeight_injOn_weightedDifferenceKernel
    {W : Set ℤ} {w₀ : ℤ} (hw₀ : w₀ ∈ W)
    (hprimitive : IsPrimitiveWeightSet W) :
    Set.InjOn (fun x : A => w₀ • x)
      (weightedDifferenceKernel W w₀ A : Set A) := by
  intro x hx y hy hxy
  have heq :
      (⟨x, hx⟩ : weightedDifferenceKernel W w₀ A) =
        (⟨y, hy⟩ : weightedDifferenceKernel W w₀ A) :=
    (weightedBaseWeightKernelHom_injective (A := A) hw₀ hprimitive) hxy
  exact congrArg Subtype.val heq

end GaoLean

#print axioms GaoLean.weightedDifferenceExponentSubgroup_eq_zmultiples
#print axioms GaoLean.weightedDifferenceModulus_dvd_exponent
#print axioms GaoLean.mem_weightedDifferenceKernel_iff_singletonLocus
#print axioms GaoLean.mem_weightedDifferenceKernel_iff_weightedValueBlock_card_eq_one
#print axioms GaoLean.quotientLayer_weightedValueBlock_card_eq_one
#print axioms GaoLean.weightedDifferenceQuotientEquivRange
#print axioms GaoLean.weightedBaseWeightKernelHom_injective
#print axioms GaoLean.weightedBaseWeight_injOn_weightedDifferenceKernel
