import GaoLean.PGGMOClaimBMaximal
import Mathlib.Data.Fintype.EquivFin

/-!
# The honest high-multiplicity core of ordinary GMO Claim B

This module formalizes only the algebra and labelled-occurrence bookkeeping
at the start of the proper-`K` high-multiplicity branch.  A nonzero centered
quotient value is represented by actual source occurrences; the corresponding
extension subgroup is the inverse image of the cyclic quotient subgroup it
generates.  No enlarged Claim-B partition or terminal witness is asserted.

The source sequence is never collapsed to a value set.  Both the repeated
nonzero quotient positions and the compensating positions in the original
`g + K` reserve are retained as injections into `Occurrence xs`.
-/

namespace GaoLean

open scoped BigOperators Pointwise

universe u

variable {A : Type u} [AddCommGroup A] [Fintype A]

section CenteredFibers

/-- The value of a source occurrence after translating the Claim-B center to
zero and quotienting by the current witness subgroup. -/
noncomputable def OrdinaryGMOClaimBOutput.centeredQuotientValue
    {xs : List A} {seed : Selection xs} {n : ℕ}
    (W : OrdinaryGMOClaimBOutput xs seed n) (i : Occurrence xs) : A ⧸ W.K :=
  QuotientAddGroup.mk' W.K (occurrenceValue xs i - W.g)

/-- The genuine labelled source fiber above one centered quotient value. -/
noncomputable def OrdinaryGMOClaimBOutput.sourceQuotientFiber
    {xs : List A} {seed : Selection xs} {n : ℕ}
    (W : OrdinaryGMOClaimBOutput xs seed n) (z : A ⧸ W.K) : Selection xs := by
  classical
  exact (Finset.univ : Selection xs).filter fun i ↦
    W.centeredQuotientValue i = z

@[simp]
theorem OrdinaryGMOClaimBOutput.mem_sourceQuotientFiber_iff
    {xs : List A} {seed : Selection xs} {n : ℕ}
    (W : OrdinaryGMOClaimBOutput xs seed n) (z : A ⧸ W.K)
    (i : Occurrence xs) :
    i ∈ W.sourceQuotientFiber z ↔ W.centeredQuotientValue i = z := by
  classical
  simp [OrdinaryGMOClaimBOutput.sourceQuotientFiber]

/-- The literal complement of the centered zero fiber. -/
noncomputable def OrdinaryGMOClaimBOutput.sourceNonzeroQuotientOccurrences
    {xs : List A} {seed : Selection xs} {n : ℕ}
    (W : OrdinaryGMOClaimBOutput xs seed n) : Selection xs := by
  classical
  exact (Finset.univ : Selection xs) \ W.sourceQuotientFiber 0

@[simp]
theorem OrdinaryGMOClaimBOutput.mem_sourceNonzeroQuotientOccurrences_iff
    {xs : List A} {seed : Selection xs} {n : ℕ}
    (W : OrdinaryGMOClaimBOutput xs seed n) (i : Occurrence xs) :
    i ∈ W.sourceNonzeroQuotientOccurrences ↔
      W.centeredQuotientValue i ≠ 0 := by
  classical
  simp [OrdinaryGMOClaimBOutput.sourceNonzeroQuotientOccurrences]

theorem OrdinaryGMOClaimBOutput.sourceQuotientFiber_subset_sourceNonzeroOccurrences
    {xs : List A} {seed : Selection xs} {n : ℕ}
    (W : OrdinaryGMOClaimBOutput xs seed n) {z : A ⧸ W.K}
    (hz : z ≠ 0) :
    W.sourceQuotientFiber z ⊆ W.sourceNonzeroQuotientOccurrences := by
  intro i hi
  apply (W.mem_sourceNonzeroQuotientOccurrences_iff i).2
  rw [(W.mem_sourceQuotientFiber_iff z i).1 hi]
  exact hz

/-- A representative of `z`, translated back to the original affine center.
The definition uses only surjectivity of the quotient map. -/
noncomputable def OrdinaryGMOClaimBOutput.quotientRepresentative
    {xs : List A} {seed : Selection xs} {n : ℕ}
    (W : OrdinaryGMOClaimBOutput xs seed n) (z : A ⧸ W.K) : A :=
  Classical.choose (QuotientAddGroup.mk'_surjective W.K z) + W.g

theorem OrdinaryGMOClaimBOutput.centeredQuotientValue_representative
    {xs : List A} {seed : Selection xs} {n : ℕ}
    (W : OrdinaryGMOClaimBOutput xs seed n) (z : A ⧸ W.K) :
    QuotientAddGroup.mk' W.K (W.quotientRepresentative z - W.g) = z := by
  simpa [OrdinaryGMOClaimBOutput.quotientRepresentative] using
    Classical.choose_spec (QuotientAddGroup.mk'_surjective W.K z)

end CenteredFibers

section CyclicExtension

/-- The quotient subgroup generated by the heavy nonzero quotient value. -/
def OrdinaryGMOClaimBOutput.highMultiplicityQuotientSubgroup
    {xs : List A} {seed : Selection xs} {n : ℕ}
    (W : OrdinaryGMOClaimBOutput xs seed n) (z : A ⧸ W.K) :
    AddSubgroup (A ⧸ W.K) :=
  AddSubgroup.closure ({z} : Set (A ⧸ W.K))

/-- The honest extension of `K`: the inverse image of `closure {z}` in
`A / K`.  This is exactly the comap version of `K ⊔ closure {a - g}` for any
representative `a` of `z`. -/
def OrdinaryGMOClaimBOutput.highMultiplicityExtensionSubgroup
    {xs : List A} {seed : Selection xs} {n : ℕ}
    (W : OrdinaryGMOClaimBOutput xs seed n) (z : A ⧸ W.K) : AddSubgroup A :=
  (W.highMultiplicityQuotientSubgroup z).comap
    (QuotientAddGroup.mk' W.K)

theorem OrdinaryGMOClaimBOutput.K_le_highMultiplicityExtensionSubgroup
    {xs : List A} {seed : Selection xs} {n : ℕ}
    (W : OrdinaryGMOClaimBOutput xs seed n) (z : A ⧸ W.K) :
    W.K ≤ W.highMultiplicityExtensionSubgroup z := by
  intro x hx
  change QuotientAddGroup.mk' W.K x ∈
    W.highMultiplicityQuotientSubgroup z
  have hx0 : QuotientAddGroup.mk' W.K x = 0 :=
    (QuotientAddGroup.eq_zero_iff x).2 hx
  rw [hx0]
  exact AddSubgroup.zero_mem _

theorem OrdinaryGMOClaimBOutput.centeredRepresentative_mem_extension
    {xs : List A} {seed : Selection xs} {n : ℕ}
    (W : OrdinaryGMOClaimBOutput xs seed n) (z : A ⧸ W.K) :
    W.quotientRepresentative z - W.g ∈
      W.highMultiplicityExtensionSubgroup z := by
  change QuotientAddGroup.mk' W.K (W.quotientRepresentative z - W.g) ∈
    AddSubgroup.closure ({z} : Set (A ⧸ W.K))
  rw [W.centeredQuotientValue_representative z]
  exact AddSubgroup.subset_closure (Set.mem_singleton z)

/-- A nonzero quotient value makes the extension genuinely strict. -/
theorem OrdinaryGMOClaimBOutput.K_lt_highMultiplicityExtensionSubgroup
    {xs : List A} {seed : Selection xs} {n : ℕ}
    (W : OrdinaryGMOClaimBOutput xs seed n) {z : A ⧸ W.K}
    (hz : z ≠ 0) :
    W.K < W.highMultiplicityExtensionSubgroup z := by
  refine lt_of_le_of_ne (W.K_le_highMultiplicityExtensionSubgroup z) ?_
  intro hEq
  have haK : W.quotientRepresentative z - W.g ∈ W.K := by
    rw [hEq]
    exact W.centeredRepresentative_mem_extension z
  have hz0 : z = 0 := by
    rw [← W.centeredQuotientValue_representative z]
    exact (QuotientAddGroup.eq_zero_iff _).2 haK
  exact hz hz0

/-- The quotient map restricted from the extension subgroup onto the cyclic
quotient subgroup. -/
noncomputable def OrdinaryGMOClaimBOutput.highMultiplicityExtensionMap
    {xs : List A} {seed : Selection xs} {n : ℕ}
    (W : OrdinaryGMOClaimBOutput xs seed n) (z : A ⧸ W.K) :
    W.highMultiplicityExtensionSubgroup z →+
      W.highMultiplicityQuotientSubgroup z where
  toFun x := ⟨QuotientAddGroup.mk' W.K x.1, x.2⟩
  map_zero' := by ext; simp
  map_add' x y := by ext; simp

theorem OrdinaryGMOClaimBOutput.highMultiplicityExtensionMap_surjective
    {xs : List A} {seed : Selection xs} {n : ℕ}
    (W : OrdinaryGMOClaimBOutput xs seed n) (z : A ⧸ W.K) :
    Function.Surjective (W.highMultiplicityExtensionMap z) := by
  intro q
  obtain ⟨a, ha⟩ := QuotientAddGroup.mk'_surjective W.K q.1
  have haL : a ∈ W.highMultiplicityExtensionSubgroup z := by
    change QuotientAddGroup.mk' W.K a ∈ W.highMultiplicityQuotientSubgroup z
    rw [ha]
    exact q.2
  refine ⟨⟨a, haL⟩, ?_⟩
  apply Subtype.ext
  exact ha

theorem OrdinaryGMOClaimBOutput.highMultiplicityExtensionMap_ker
    {xs : List A} {seed : Selection xs} {n : ℕ}
    (W : OrdinaryGMOClaimBOutput xs seed n) (z : A ⧸ W.K) :
    (W.highMultiplicityExtensionMap z).ker =
      internalAddSubgroup W.K (W.highMultiplicityExtensionSubgroup z) := by
  ext x
  change W.highMultiplicityExtensionMap z x = 0 ↔ x.1 ∈ W.K
  constructor
  · intro hx
    have hxq : QuotientAddGroup.mk' W.K x.1 = 0 :=
      congrArg Subtype.val hx
    exact (QuotientAddGroup.eq_zero_iff x.1).1 hxq
  · intro hx
    apply Subtype.ext
    exact (QuotientAddGroup.eq_zero_iff x.1).2 hx

/-- First-isomorphism identification `L/K ≃ closure {z}`. -/
noncomputable def OrdinaryGMOClaimBOutput.highMultiplicityInternalQuotientEquiv
    {xs : List A} {seed : Selection xs} {n : ℕ}
    (W : OrdinaryGMOClaimBOutput xs seed n) (z : A ⧸ W.K) :
    W.highMultiplicityExtensionSubgroup z ⧸
        internalAddSubgroup W.K (W.highMultiplicityExtensionSubgroup z) ≃+
      W.highMultiplicityQuotientSubgroup z :=
  (QuotientAddGroup.quotientAddEquivOfEq
      (W.highMultiplicityExtensionMap_ker z).symm).trans
    (QuotientAddGroup.quotientKerEquivOfSurjective
      (W.highMultiplicityExtensionMap z)
      (W.highMultiplicityExtensionMap_surjective z))

/-- Exact transport of the canonical invariant across `L/K ≃ closure {z}`. -/
theorem OrdinaryGMOClaimBOutput.pGroupDStar_internalQuotient_eq_cyclic
    {xs : List A} {seed : Selection xs} {n : ℕ}
    (W : OrdinaryGMOClaimBOutput xs seed n) (z : A ⧸ W.K) :
    pGroupDStar
        (W.highMultiplicityExtensionSubgroup z ⧸
          internalAddSubgroup W.K (W.highMultiplicityExtensionSubgroup z)) =
      pGroupDStar (W.highMultiplicityQuotientSubgroup z) :=
  pGroupDStar_addEquiv (W.highMultiplicityInternalQuotientEquiv z)

/-- The subgroup--quotient convolution for the genuine extension `K ≤ L`. -/
theorem OrdinaryGMOClaimBOutput.pGroupDStar_K_add_internalQuotient_le_extension
    {xs : List A} {seed : Selection xs} {n : ℕ}
    (W : OrdinaryGMOClaimBOutput xs seed n) (z : A ⧸ W.K) :
    pGroupDStar W.K +
        pGroupDStar
          (W.highMultiplicityExtensionSubgroup z ⧸
            internalAddSubgroup W.K (W.highMultiplicityExtensionSubgroup z)) ≤
      pGroupDStar (W.highMultiplicityExtensionSubgroup z) :=
  pGroupDStar_internal_of_le W.K (W.highMultiplicityExtensionSubgroup z)
    (W.K_le_highMultiplicityExtensionSubgroup z)

/-- The required cyclic/internal quotient length is no larger than the full
ambient quotient length appearing in the high-multiplicity hypothesis. -/
theorem OrdinaryGMOClaimBOutput.pGroupDStar_internalQuotient_le_ambientQuotient
    {xs : List A} {seed : Selection xs} {n : ℕ}
    (W : OrdinaryGMOClaimBOutput xs seed n) (z : A ⧸ W.K) :
    pGroupDStar
        (W.highMultiplicityExtensionSubgroup z ⧸
          internalAddSubgroup W.K (W.highMultiplicityExtensionSubgroup z)) ≤
      pGroupDStar (A ⧸ W.K) := by
  letI : Fintype (A ⧸ W.K) := Fintype.ofFinite (A ⧸ W.K)
  have hconv := pGroupDStar_subgroup_quotient_le
    (W.highMultiplicityQuotientSubgroup z)
  have heq := W.pGroupDStar_internalQuotient_eq_cyclic z
  omega

/-- Every subgroup has canonical `d*` at most the ambient canonical `d*`,
hence at most `n` under the ambient Davenport-star budget. -/
theorem pGroupDStar_addSubgroup_le_of_ambient_le
    (L : AddSubgroup A) {n : ℕ} (hn : pGroupDStar A ≤ n) :
    pGroupDStar L ≤ n := by
  have hconv := pGroupDStar_subgroup_quotient_le L
  omega

end CyclicExtension

section PGroupInheritance

variable {p : ℕ}

theorem OrdinaryGMOClaimBOutput.isPGroup_highMultiplicityQuotientSubgroup
    (hA : IsPGroup p (Multiplicative A))
    {xs : List A} {seed : Selection xs} {n : ℕ}
    (W : OrdinaryGMOClaimBOutput xs seed n) (z : A ⧸ W.K) :
    IsPGroup p (Multiplicative (W.highMultiplicityQuotientSubgroup z)) := by
  have hQ : IsPGroup p (Multiplicative (A ⧸ W.K)) :=
    isPGroup_multiplicative_quotient p hA W.K
  exact isPGroup_multiplicative_addSubgroup p hQ
    (W.highMultiplicityQuotientSubgroup z)

theorem OrdinaryGMOClaimBOutput.isPGroup_highMultiplicityExtensionSubgroup
    (hA : IsPGroup p (Multiplicative A))
    {xs : List A} {seed : Selection xs} {n : ℕ}
    (W : OrdinaryGMOClaimBOutput xs seed n) (z : A ⧸ W.K) :
    IsPGroup p (Multiplicative (W.highMultiplicityExtensionSubgroup z)) :=
  isPGroup_multiplicative_addSubgroup p hA
    (W.highMultiplicityExtensionSubgroup z)

theorem OrdinaryGMOClaimBOutput.isPGroup_highMultiplicityInternalQuotient
    (hA : IsPGroup p (Multiplicative A))
    {xs : List A} {seed : Selection xs} {n : ℕ}
    (W : OrdinaryGMOClaimBOutput xs seed n) (z : A ⧸ W.K) :
    IsPGroup p
      (Multiplicative
        (W.highMultiplicityExtensionSubgroup z ⧸
          internalAddSubgroup W.K (W.highMultiplicityExtensionSubgroup z))) := by
  have hL := W.isPGroup_highMultiplicityExtensionSubgroup hA z
  exact isPGroup_multiplicative_quotient p hL
    (internalAddSubgroup W.K (W.highMultiplicityExtensionSubgroup z))

end PGroupInheritance

section LabelledSelection

/-- The exact number of nonzero-fiber occurrences needed for the extension
`K < L`: namely `d*(L/K)`. -/
noncomputable def OrdinaryGMOClaimBOutput.highMultiplicityLength
    {xs : List A} {seed : Selection xs} {n : ℕ}
    (W : OrdinaryGMOClaimBOutput xs seed n) (z : A ⧸ W.K) : ℕ :=
  pGroupDStar
    (W.highMultiplicityExtensionSubgroup z ⧸
      internalAddSubgroup W.K (W.highMultiplicityExtensionSubgroup z))

/-- Honest labelled data extracted in the high-multiplicity branch.  Both
families are injections into the original source occurrence type. -/
structure OrdinaryGMOClaimBHighMultiplicityCore
    {xs : List A} {seed : Selection xs} {n : ℕ}
    (W : OrdinaryGMOClaimBOutput xs seed n) (z : A ⧸ W.K) where
  proper : W.K ≠ ⊤
  nonzero : z ≠ 0
  highSource : Fin (W.highMultiplicityLength z) ↪ Occurrence xs
  high_mem_fiber : ∀ t, highSource t ∈ W.sourceQuotientFiber z
  reserveSource : Fin (W.highMultiplicityLength z) ↪ Occurrence xs
  reserve_mem : ∀ t,
    reserveSource t ∈ W.partition.unusedInAddCoset W.K W.g

/-- The high multiplicity bound supplies exactly `d*(L/K)` genuine nonzero
source positions, while the Claim-B remaining-occurrence ledger supplies the
same number of distinct zero-fiber reserve positions. -/
theorem exists_ordinaryGMOClaimBHighMultiplicityCore
    {xs : List A} {seed : Selection xs} {n : ℕ}
    (W : OrdinaryGMOClaimBOutput xs seed n)
    (hKtop : W.K ≠ ⊤) (hambient : pGroupDStar A ≤ n)
    (z : A ⧸ W.K) (hz : z ≠ 0)
    (hmult : pGroupDStar (A ⧸ W.K) ≤
      (W.sourceQuotientFiber z).card) :
    Nonempty (OrdinaryGMOClaimBHighMultiplicityCore W z) := by
  classical
  let r := W.highMultiplicityLength z
  have hrAmbient : r ≤ pGroupDStar (A ⧸ W.K) := by
    simpa only [r, OrdinaryGMOClaimBOutput.highMultiplicityLength] using
      W.pGroupDStar_internalQuotient_le_ambientQuotient z
  have hrFiber : r ≤ (W.sourceQuotientFiber z).card :=
    hrAmbient.trans hmult
  obtain ⟨highSet, hhighSub, hhighCard⟩ :=
    Finset.exists_subset_card_eq hrFiber
  let highSource : Fin r ↪ Occurrence xs :=
    (highSet.equivFinOfCardEq hhighCard).symm.toEmbedding.trans
      (Function.Embedding.subtype _)
  have hhigh (t : Fin r) : highSource t ∈ W.sourceQuotientFiber z := by
    exact hhighSub ((highSet.equivFinOfCardEq hhighCard).symm t).property
  have hLlen : pGroupDStar (W.highMultiplicityExtensionSubgroup z) ≤ n :=
    pGroupDStar_addSubgroup_le_of_ambient_le
      (W.highMultiplicityExtensionSubgroup z) hambient
  have hconv := W.pGroupDStar_K_add_internalQuotient_le_extension z
  have hrSub : r ≤ n - pGroupDStar W.K := by
    dsimp only [r, OrdinaryGMOClaimBOutput.highMultiplicityLength]
    omega
  have hrReserve : r ≤
      (W.partition.unusedInAddCoset W.K W.g).card := by
    have hremaining := W.remaining_in_coset
    omega
  obtain ⟨reserveSet, hreserveSub, hreserveCard⟩ :=
    Finset.exists_subset_card_eq hrReserve
  let reserveSource : Fin r ↪ Occurrence xs :=
    (reserveSet.equivFinOfCardEq hreserveCard).symm.toEmbedding.trans
      (Function.Embedding.subtype _)
  have hreserve (t : Fin r) :
      reserveSource t ∈
        W.partition.unusedInAddCoset W.K W.g := by
    exact hreserveSub
      ((reserveSet.equivFinOfCardEq hreserveCard).symm t).property
  refine ⟨{
    proper := hKtop
    nonzero := hz
    highSource := highSource
    high_mem_fiber := hhigh
    reserveSource := reserveSource
    reserve_mem := hreserve
  }⟩

/-- Range of the selected high-fiber source injection. -/
noncomputable def OrdinaryGMOClaimBHighMultiplicityCore.highSourceRange
    {xs : List A} {seed : Selection xs} {n : ℕ}
    {W : OrdinaryGMOClaimBOutput xs seed n} {z : A ⧸ W.K}
    (D : OrdinaryGMOClaimBHighMultiplicityCore W z) : Selection xs := by
  classical
  exact Finset.univ.map D.highSource

/-- Range of the selected zero-fiber reserve injection. -/
noncomputable def OrdinaryGMOClaimBHighMultiplicityCore.reserveSourceRange
    {xs : List A} {seed : Selection xs} {n : ℕ}
    {W : OrdinaryGMOClaimBOutput xs seed n} {z : A ⧸ W.K}
    (D : OrdinaryGMOClaimBHighMultiplicityCore W z) : Selection xs := by
  classical
  exact Finset.univ.map D.reserveSource

@[simp]
theorem OrdinaryGMOClaimBHighMultiplicityCore.card_highSourceRange
    {xs : List A} {seed : Selection xs} {n : ℕ}
    {W : OrdinaryGMOClaimBOutput xs seed n} {z : A ⧸ W.K}
    (D : OrdinaryGMOClaimBHighMultiplicityCore W z) :
    D.highSourceRange.card = W.highMultiplicityLength z := by
  classical
  simp [OrdinaryGMOClaimBHighMultiplicityCore.highSourceRange]

@[simp]
theorem OrdinaryGMOClaimBHighMultiplicityCore.card_reserveSourceRange
    {xs : List A} {seed : Selection xs} {n : ℕ}
    {W : OrdinaryGMOClaimBOutput xs seed n} {z : A ⧸ W.K}
    (D : OrdinaryGMOClaimBHighMultiplicityCore W z) :
    D.reserveSourceRange.card = W.highMultiplicityLength z := by
  classical
  simp [OrdinaryGMOClaimBHighMultiplicityCore.reserveSourceRange]

theorem OrdinaryGMOClaimBHighMultiplicityCore.highSource_mem_nonzeroOccurrences
    {xs : List A} {seed : Selection xs} {n : ℕ}
    {W : OrdinaryGMOClaimBOutput xs seed n} {z : A ⧸ W.K}
    (D : OrdinaryGMOClaimBHighMultiplicityCore W z) (hz : z ≠ 0)
    (t : Fin (W.highMultiplicityLength z)) :
    D.highSource t ∈ W.sourceNonzeroQuotientOccurrences :=
  W.sourceQuotientFiber_subset_sourceNonzeroOccurrences hz
    (D.high_mem_fiber t)

theorem OrdinaryGMOClaimBHighMultiplicityCore.highSource_not_mem_support
    {xs : List A} {seed : Selection xs} {n : ℕ}
    {W : OrdinaryGMOClaimBOutput xs seed n} {z : A ⧸ W.K}
    (D : OrdinaryGMOClaimBHighMultiplicityCore W z) (hz : z ≠ 0)
    (t : Fin (W.highMultiplicityLength z)) :
    D.highSource t ∉ W.partition.support := by
  intro ht
  have hcoset := W.support_in_coset (D.highSource t) ht
  have hmemK : occurrenceValue xs (D.highSource t) - W.g ∈ W.K :=
    (mem_addCosetFinset_iff W.K W.g
      (occurrenceValue xs (D.highSource t))).1 hcoset
  have hzero : W.centeredQuotientValue (D.highSource t) = 0 :=
    (QuotientAddGroup.eq_zero_iff _).2 hmemK
  have hzFiber :=
    (W.mem_sourceQuotientFiber_iff z (D.highSource t)).1
      (D.high_mem_fiber t)
  exact hz (hzFiber.symm.trans hzero)

theorem OrdinaryGMOClaimBHighMultiplicityCore.reserveSource_centered_eq_zero
    {xs : List A} {seed : Selection xs} {n : ℕ}
    {W : OrdinaryGMOClaimBOutput xs seed n} {z : A ⧸ W.K}
    (D : OrdinaryGMOClaimBHighMultiplicityCore W z)
    (t : Fin (W.highMultiplicityLength z)) :
    W.centeredQuotientValue (D.reserveSource t) = 0 := by
  have hcoset :=
    (W.partition.mem_unusedInAddCoset_iff W.K W.g
      (D.reserveSource t)).1 (D.reserve_mem t) |>.2
  exact (QuotientAddGroup.eq_zero_iff _).2
    ((mem_addCosetFinset_iff W.K W.g
      (occurrenceValue xs (D.reserveSource t))).1 hcoset)

theorem OrdinaryGMOClaimBHighMultiplicityCore.reserveSource_not_mem_support
    {xs : List A} {seed : Selection xs} {n : ℕ}
    {W : OrdinaryGMOClaimBOutput xs seed n} {z : A ⧸ W.K}
    (D : OrdinaryGMOClaimBHighMultiplicityCore W z)
    (t : Fin (W.highMultiplicityLength z)) :
    D.reserveSource t ∉ W.partition.support :=
  (W.partition.mem_unusedInAddCoset_iff W.K W.g
    (D.reserveSource t)).1 (D.reserve_mem t) |>.1

/-- A nonzero-fiber source position can never equal a chosen zero-fiber
reserve position. -/
theorem OrdinaryGMOClaimBHighMultiplicityCore.highSource_ne_reserveSource
    {xs : List A} {seed : Selection xs} {n : ℕ}
    {W : OrdinaryGMOClaimBOutput xs seed n} {z : A ⧸ W.K}
    (D : OrdinaryGMOClaimBHighMultiplicityCore W z) (hz : z ≠ 0)
    (s t : Fin (W.highMultiplicityLength z)) :
    D.highSource s ≠ D.reserveSource t := by
  intro heq
  have hhigh :=
    (W.mem_sourceQuotientFiber_iff z (D.highSource s)).1
      (D.high_mem_fiber s)
  have hreserve := D.reserveSource_centered_eq_zero t
  rw [heq] at hhigh
  exact hz (hhigh.symm.trans hreserve)

theorem OrdinaryGMOClaimBHighMultiplicityCore.disjoint_sourceRanges
    {xs : List A} {seed : Selection xs} {n : ℕ}
    {W : OrdinaryGMOClaimBOutput xs seed n} {z : A ⧸ W.K}
    (D : OrdinaryGMOClaimBHighMultiplicityCore W z) (hz : z ≠ 0) :
    Disjoint D.highSourceRange D.reserveSourceRange := by
  classical
  rw [Finset.disjoint_left]
  intro i hiHigh hiReserve
  obtain ⟨s, -, hs⟩ := Finset.mem_map.mp hiHigh
  obtain ⟨t, -, ht⟩ := Finset.mem_map.mp hiReserve
  exact D.highSource_ne_reserveSource hz s t (hs.trans ht.symm)

theorem OrdinaryGMOClaimBHighMultiplicityCore.highSourceRange_disjoint_support
    {xs : List A} {seed : Selection xs} {n : ℕ}
    {W : OrdinaryGMOClaimBOutput xs seed n} {z : A ⧸ W.K}
    (D : OrdinaryGMOClaimBHighMultiplicityCore W z) (hz : z ≠ 0) :
    Disjoint D.highSourceRange W.partition.support := by
  classical
  rw [Finset.disjoint_left]
  intro i hiHigh hiSupport
  obtain ⟨t, -, rfl⟩ := Finset.mem_map.mp hiHigh
  exact D.highSource_not_mem_support hz t hiSupport

theorem OrdinaryGMOClaimBHighMultiplicityCore.reserveSourceRange_disjoint_support
    {xs : List A} {seed : Selection xs} {n : ℕ}
    {W : OrdinaryGMOClaimBOutput xs seed n} {z : A ⧸ W.K}
    (D : OrdinaryGMOClaimBHighMultiplicityCore W z) :
    Disjoint D.reserveSourceRange W.partition.support := by
  classical
  rw [Finset.disjoint_left]
  intro i hiReserve hiSupport
  obtain ⟨t, -, rfl⟩ := Finset.mem_map.mp hiReserve
  exact D.reserveSource_not_mem_support t hiSupport

/-- Every selected high-fiber value lies in the affine `g + L` coset. -/
theorem OrdinaryGMOClaimBHighMultiplicityCore.highSource_value_mem_extensionCoset
    {xs : List A} {seed : Selection xs} {n : ℕ}
    {W : OrdinaryGMOClaimBOutput xs seed n} {z : A ⧸ W.K}
    (D : OrdinaryGMOClaimBHighMultiplicityCore W z)
    (t : Fin (W.highMultiplicityLength z)) :
    occurrenceValue xs (D.highSource t) ∈
      addCosetFinset (W.highMultiplicityExtensionSubgroup z) W.g := by
  apply (mem_addCosetFinset_iff
    (W.highMultiplicityExtensionSubgroup z) W.g _).2
  change W.centeredQuotientValue (D.highSource t) ∈
    W.highMultiplicityQuotientSubgroup z
  rw [(W.mem_sourceQuotientFiber_iff z (D.highSource t)).1
    (D.high_mem_fiber t)]
  exact AddSubgroup.subset_closure (Set.mem_singleton z)

/-- In the internal quotient `L/K`, every chosen high value has exactly the
same class as the fixed representative of `z`. -/
theorem OrdinaryGMOClaimBHighMultiplicityCore.highSource_internalQuotient_eq_representative
    {xs : List A} {seed : Selection xs} {n : ℕ}
    {W : OrdinaryGMOClaimBOutput xs seed n} {z : A ⧸ W.K}
    (D : OrdinaryGMOClaimBHighMultiplicityCore W z)
    (t : Fin (W.highMultiplicityLength z)) :
    QuotientAddGroup.mk'
        (internalAddSubgroup W.K
          (W.highMultiplicityExtensionSubgroup z))
        (⟨occurrenceValue xs (D.highSource t) - W.g,
          (mem_addCosetFinset_iff
            (W.highMultiplicityExtensionSubgroup z) W.g _).1
              (D.highSource_value_mem_extensionCoset t)⟩ :
          W.highMultiplicityExtensionSubgroup z) =
      QuotientAddGroup.mk'
        (internalAddSubgroup W.K
          (W.highMultiplicityExtensionSubgroup z))
        (⟨W.quotientRepresentative z - W.g,
          W.centeredRepresentative_mem_extension z⟩ :
          W.highMultiplicityExtensionSubgroup z) := by
  apply QuotientAddGroup.eq_iff_sub_mem.mpr
  change (occurrenceValue xs (D.highSource t) - W.g) -
      (W.quotientRepresentative z - W.g) ∈ W.K
  apply QuotientAddGroup.eq_iff_sub_mem.mp
  calc
    QuotientAddGroup.mk' W.K
        (occurrenceValue xs (D.highSource t) - W.g) = z :=
      (W.mem_sourceQuotientFiber_iff z (D.highSource t)).1
        (D.high_mem_fiber t)
    _ = QuotientAddGroup.mk' W.K
        (W.quotientRepresentative z - W.g) :=
      (W.centeredQuotientValue_representative z).symm

end LabelledSelection

end GaoLean

#print axioms GaoLean.OrdinaryGMOClaimBOutput.K_lt_highMultiplicityExtensionSubgroup
#print axioms GaoLean.OrdinaryGMOClaimBOutput.highMultiplicityInternalQuotientEquiv
#print axioms GaoLean.OrdinaryGMOClaimBOutput.pGroupDStar_K_add_internalQuotient_le_extension
#print axioms GaoLean.exists_ordinaryGMOClaimBHighMultiplicityCore
#print axioms GaoLean.OrdinaryGMOClaimBHighMultiplicityCore.disjoint_sourceRanges
#print axioms GaoLean.OrdinaryGMOClaimBHighMultiplicityCore.highSource_internalQuotient_eq_representative
