import GaoLean.PGGMOClaimBCore
import GaoLean.PGGMOClaimBAlgebra

/-!
# The intermediate subgroup generated by the Claim B common core

This module constructs the intermediate subgroup used in the proper-
subgroup branch of ordinary GMO Claim B.  Nothing is assumed to be
`K`-saturated.  Starting from `g ∈ commonCore`, it centers the quotient
image modulo `H`, takes its generated subgroup `L`, and defines
`K = (mk H)⁻¹(L)`.

The resulting geometry supplies the exact inputs needed by the already
proved subgroup--quotient `d*` convolution and affine Lemma 4.2.
-/

namespace GaoLean

open scoped BigOperators Pointwise

universe u

variable {A : Type u} [AddCommGroup A] [Fintype A]

section Definitions

/-- The quotient image of the common core, translated so that the chosen
common-core point becomes zero. -/
noncomputable def centeredCommonCoreQuotient
    {xs : List A} {n m : ℕ} (P : Theorem21SetPartition xs n m)
    (H : AddSubgroup A) (g : A) : Finset (A ⧸ H) := by
  classical
  exact (quotientLayer H (P.commonCore H)).image fun q ↦
    q - QuotientAddGroup.mk' H g

/-- The subgroup `L ≤ A/H` generated by the centered common-core image. -/
noncomputable def claimBIntermediateQuotientSubgroup
    {xs : List A} {n m : ℕ} (P : Theorem21SetPartition xs n m)
    (H : AddSubgroup A) (g : A) : AddSubgroup (A ⧸ H) :=
  AddSubgroup.closure (centeredCommonCoreQuotient P H g : Set (A ⧸ H))

/-- The intermediate subgroup `K ≤ A`, defined as the full preimage of
`L` under the quotient map modulo `H`. -/
noncomputable def claimBIntermediateSubgroup
    {xs : List A} {n m : ℕ} (P : Theorem21SetPartition xs n m)
    (H : AddSubgroup A) (g : A) : AddSubgroup A :=
  (claimBIntermediateQuotientSubgroup P H g).comap
    (QuotientAddGroup.mk' H)

/-- The centered finite generating set, regarded inside its generated
subgroup `L`.  This is the literal input required by affine Lemma 4.2. -/
noncomputable def claimBCenteredGenerators
    {xs : List A} {n m : ℕ} (P : Theorem21SetPartition xs n m)
    (H : AddSubgroup A) (g : A) :
    Finset (claimBIntermediateQuotientSubgroup P H g) := by
  classical
  let U := centeredCommonCoreQuotient P H g
  let L := claimBIntermediateQuotientSubgroup P H g
  exact U.attach.image fun q ↦
    (⟨q.1, AddSubgroup.subset_closure q.2⟩ : L)

end Definitions

section BasicGeometry

@[simp]
theorem mem_centeredCommonCoreQuotient_iff
    {xs : List A} {n m : ℕ} (P : Theorem21SetPartition xs n m)
    (H : AddSubgroup A) (g : A) (q : A ⧸ H) :
    q ∈ centeredCommonCoreQuotient P H g ↔
      ∃ r ∈ quotientLayer H (P.commonCore H),
        r - QuotientAddGroup.mk' H g = q := by
  classical
  simp [centeredCommonCoreQuotient]

/-- Centering at a common-core point puts zero in the finite quotient
generating set. -/
theorem zero_mem_centeredCommonCoreQuotient
    {xs : List A} {n m : ℕ} (P : Theorem21SetPartition xs n m)
    (H : AddSubgroup A) (g : A) (hg : g ∈ P.commonCore H) :
    0 ∈ centeredCommonCoreQuotient P H g := by
  classical
  apply (mem_centeredCommonCoreQuotient_iff P H g 0).2
  refine ⟨QuotientAddGroup.mk' H g, ?_, sub_self _⟩
  exact (mem_quotientLayer_iff H (P.commonCore H) _).2
    ⟨g, hg, rfl⟩

/-- By construction the centered quotient layer generates exactly `L`. -/
theorem closure_centeredCommonCoreQuotient
    {xs : List A} {n m : ℕ} (P : Theorem21SetPartition xs n m)
    (H : AddSubgroup A) (g : A) :
    AddSubgroup.closure
        (centeredCommonCoreQuotient P H g : Set (A ⧸ H)) =
      claimBIntermediateQuotientSubgroup P H g := rfl

/-- The original subgroup is contained in its common-core intermediate
subgroup. -/
theorem subgroup_le_claimBIntermediateSubgroup
    {xs : List A} {n m : ℕ} (P : Theorem21SetPartition xs n m)
    (H : AddSubgroup A) (g : A) :
    H ≤ claimBIntermediateSubgroup P H g := by
  intro h hh
  change QuotientAddGroup.mk' H h ∈
    claimBIntermediateQuotientSubgroup P H g
  have hzero : QuotientAddGroup.mk' H h = 0 := by
    apply QuotientAddGroup.eq_iff_sub_mem.mpr
    simpa using hh
  rw [hzero]
  exact AddSubgroup.zero_mem _

/-- Every common-core value lies in the single coset `g + K`.  This is a
consequence of the definition of `K`, not a saturation assumption. -/
theorem commonCore_subset_addCosetFinset_claimBIntermediateSubgroup
    {xs : List A} {n m : ℕ} (P : Theorem21SetPartition xs n m)
    (H : AddSubgroup A) (g : A) (hg : g ∈ P.commonCore H) :
    P.commonCore H ⊆
      addCosetFinset (claimBIntermediateSubgroup P H g) g := by
  classical
  intro x hx
  apply (mem_addCosetFinset_iff
    (claimBIntermediateSubgroup P H g) g x).2
  change QuotientAddGroup.mk' H (x - g) ∈
    claimBIntermediateQuotientSubgroup P H g
  have hqx : QuotientAddGroup.mk' H x ∈
      quotientLayer H (P.commonCore H) :=
    (mem_quotientLayer_iff H (P.commonCore H) _).2 ⟨x, hx, rfl⟩
  have hcenter : QuotientAddGroup.mk' H x -
      QuotientAddGroup.mk' H g ∈
      claimBIntermediateQuotientSubgroup P H g :=
    AddSubgroup.subset_closure
      ((mem_centeredCommonCoreQuotient_iff P H g _).2
        ⟨QuotientAddGroup.mk' H x, hqx, rfl⟩)
  simpa using hcenter

/-- If `H` is nontrivial then the intermediate subgroup containing it is
nontrivial. -/
theorem claimBIntermediateSubgroup_ne_bot_of_H_ne_bot
    {xs : List A} {n m : ℕ} (P : Theorem21SetPartition xs n m)
    (H : AddSubgroup A) (g : A) (hH : H ≠ ⊥) :
    claimBIntermediateSubgroup P H g ≠ ⊥ := by
  intro hK
  apply hH
  apply le_antisymm
  · rw [← hK]
    exact subgroup_le_claimBIntermediateSubgroup P H g
  · exact bot_le

/-- Typeclass form of the preceding nontriviality statement. -/
theorem nontrivial_claimBIntermediateSubgroup_of_H_ne_bot
    {xs : List A} {n m : ℕ} (P : Theorem21SetPartition xs n m)
    (H : AddSubgroup A) (g : A) (hH : H ≠ ⊥) :
    Nontrivial (claimBIntermediateSubgroup P H g) :=
  (AddSubgroup.nontrivial_iff_ne_bot _).2
    (claimBIntermediateSubgroup_ne_bot_of_H_ne_bot P H g hH)

end BasicGeometry

section ThickSliceNontriviality

/-- Two distinct values in one quotient fiber force the quotienting subgroup
to be nontrivial. -/
theorem addSubgroup_ne_bot_of_cosetValueSlice_card_two_le
    {xs : List A} {n m : ℕ} (P : Theorem21SetPartition xs n m)
    (H : AddSubgroup A) (c : Fin n) (q : A ⧸ H)
    (hthick : 2 ≤ (P.cosetValueSlice H c q).card) :
    H ≠ ⊥ := by
  classical
  have hone : 1 < (P.cosetValueSlice H c q).card := by omega
  obtain ⟨x, hx, y, hy, hxy⟩ := Finset.one_lt_card.mp hone
  have hxq := (P.mem_cosetValueSlice_iff H c q x).1 hx |>.2
  have hyq := (P.mem_cosetValueSlice_iff H c q y).1 hy |>.2
  intro hH
  have hsub : x - y ∈ H :=
    QuotientAddGroup.eq_iff_sub_mem.mp (hxq.trans hyq.symm)
  rw [hH] at hsub
  have hzero : x - y = 0 := by simpa using hsub
  exact hxy (sub_eq_zero.mp hzero)

/-- A thick common quotient slice therefore makes the intermediate subgroup
nontrivial, without assuming nontriviality separately. -/
theorem claimBIntermediateSubgroup_ne_bot_of_cosetValueSlice_card_two_le
    {xs : List A} {n m : ℕ} (P : Theorem21SetPartition xs n m)
    (H : AddSubgroup A) (g : A) (c : Fin n) (q : A ⧸ H)
    (hthick : 2 ≤ (P.cosetValueSlice H c q).card) :
    claimBIntermediateSubgroup P H g ≠ ⊥ :=
  claimBIntermediateSubgroup_ne_bot_of_H_ne_bot P H g
    (addSubgroup_ne_bot_of_cosetValueSlice_card_two_le P H c q hthick)

end ThickSliceNontriviality

section CenteredGenerators

@[simp]
theorem mem_claimBCenteredGenerators_iff
    {xs : List A} {n m : ℕ} (P : Theorem21SetPartition xs n m)
    (H : AddSubgroup A) (g : A)
    (z : claimBIntermediateQuotientSubgroup P H g) :
    z ∈ claimBCenteredGenerators P H g ↔
      z.1 ∈ centeredCommonCoreQuotient P H g := by
  classical
  constructor
  · intro hz
    obtain ⟨q, hq, hqz⟩ := Finset.mem_image.mp hz
    have hval : q.1 = z.1 := congrArg Subtype.val hqz
    simpa [hval] using q.2
  · intro hz
    apply Finset.mem_image.mpr
    let q : {x // x ∈ centeredCommonCoreQuotient P H g} := ⟨z.1, hz⟩
    refine ⟨q, Finset.mem_attach _ _, ?_⟩
    apply Subtype.ext
    rfl

/-- Zero belongs to the subtype-valued centered generator set. -/
theorem zero_mem_claimBCenteredGenerators
    {xs : List A} {n m : ℕ} (P : Theorem21SetPartition xs n m)
    (H : AddSubgroup A) (g : A) (hg : g ∈ P.commonCore H) :
    0 ∈ claimBCenteredGenerators P H g := by
  apply (mem_claimBCenteredGenerators_iff P H g 0).2
  simpa using zero_mem_centeredCommonCoreQuotient P H g hg

/-- The subtype-valued centered generators generate all of `L`. -/
theorem closure_claimBCenteredGenerators_eq_top
    {xs : List A} {n m : ℕ} (P : Theorem21SetPartition xs n m)
    (H : AddSubgroup A) (g : A) :
    AddSubgroup.closure
        (claimBCenteredGenerators P H g :
          Set (claimBIntermediateQuotientSubgroup P H g)) = ⊤ := by
  apply top_unique
  intro z _
  change z ∈ AddSubgroup.closure
    (claimBCenteredGenerators P H g :
      Set (claimBIntermediateQuotientSubgroup P H g))
  let U := centeredCommonCoreQuotient P H g
  let L := claimBIntermediateQuotientSubgroup P H g
  have hz : z.1 ∈ AddSubgroup.closure (U : Set (A ⧸ H)) := by
    exact z.2
  refine AddSubgroup.closure_induction
    (p := fun q hq ↦
      (⟨q, hq⟩ : L) ∈ AddSubgroup.closure
        (claimBCenteredGenerators P H g : Set L))
    (fun q hq ↦ ?_) ?_ (fun x y hx hy hxi hyi ↦ ?_)
    (fun x hx hxi ↦ ?_) hz
  · let zq : L := ⟨q, AddSubgroup.subset_closure hq⟩
    exact AddSubgroup.subset_closure
      ((mem_claimBCenteredGenerators_iff P H g zq).2 hq)
  · exact AddSubgroup.zero_mem _
  · exact AddSubgroup.add_mem _ hxi hyi
  · exact AddSubgroup.neg_mem _ hxi

/-- Translating the subtype-valued generator set back by `ḡ` recovers
the literal quotient layer of the common core. -/
noncomputable local instance quotientFintype (H : AddSubgroup A) :
    Fintype (A ⧸ H) := Fintype.ofFinite (A ⧸ H)

theorem affineSubgroupFinset_claimBCenteredGenerators_eq_quotientLayer
    {xs : List A} {n m : ℕ} (P : Theorem21SetPartition xs n m)
    (H : AddSubgroup A) [DecidableEq (A ⧸ H)] (g : A) :
    affineSubgroupFinset
        (claimBIntermediateQuotientSubgroup P H g)
        (QuotientAddGroup.mk' H g)
        (claimBCenteredGenerators P H g) =
      quotientLayer H (P.commonCore H) := by
  classical
  ext q
  constructor
  · intro hq
    obtain ⟨z, hz, hzq⟩ := Finset.mem_image.mp hq
    have hzU := (mem_claimBCenteredGenerators_iff P H g z).1 hz
    obtain ⟨r, hr, hrz⟩ :=
      (mem_centeredCommonCoreQuotient_iff P H g z.1).1 hzU
    have hqr : QuotientAddGroup.mk' H g + z.1 = r := by
      rw [← hrz]
      abel
    have hqeq : q = r := hzq.symm.trans hqr
    rw [hqeq]
    exact hr
  · intro hq
    let z : claimBIntermediateQuotientSubgroup P H g :=
      ⟨q - QuotientAddGroup.mk' H g,
        AddSubgroup.subset_closure
          ((mem_centeredCommonCoreQuotient_iff P H g _).2
            ⟨q, hq, rfl⟩)⟩
    apply Finset.mem_image.mpr
    refine ⟨z, (mem_claimBCenteredGenerators_iff P H g z).2 ?_, ?_⟩
    · exact (mem_centeredCommonCoreQuotient_iff P H g _).2
        ⟨q, hq, rfl⟩
    · dsimp [z]
      abel

/-- The affine Lemma 4.2 is now directly applicable to the actual common-
core quotient layer. -/
theorem quotientLayer_commonCore_affine_spanning
    {xs : List A} {n m : ℕ} (P : Theorem21SetPartition xs n m)
    (H : AddSubgroup A) [DecidableEq (A ⧸ H)]
    (g : A) (hg : g ∈ P.commonCore H)
    (k : ℕ)
    (hk : pGroupDStar (claimBIntermediateQuotientSubgroup P H g) ≤ k) :
    addCosetFinset
        (claimBIntermediateQuotientSubgroup P H g)
        (k • QuotientAddGroup.mk' H g) ⊆
      iteratedFinsetSum
        (List.replicate k (quotientLayer H (P.commonCore H))) := by
  have hspan :=
    addCosetFinset_subset_iteratedFinsetSum_replicate_affine
      (claimBIntermediateQuotientSubgroup P H g)
      (QuotientAddGroup.mk' H g)
      (claimBCenteredGenerators P H g)
      (zero_mem_claimBCenteredGenerators P H g hg)
      (closure_claimBCenteredGenerators_eq_top P H g) k hk
  simpa only [
    affineSubgroupFinset_claimBCenteredGenerators_eq_quotientLayer]
    using hspan

end CenteredGenerators

section InternalQuotient

/-- The quotient map restricted from `K` onto `L`. -/
noncomputable def claimBIntermediateMap
    {xs : List A} {n m : ℕ} (P : Theorem21SetPartition xs n m)
    (H : AddSubgroup A) (g : A) :
    claimBIntermediateSubgroup P H g →+
      claimBIntermediateQuotientSubgroup P H g where
  toFun x := ⟨QuotientAddGroup.mk' H x.1, x.2⟩
  map_zero' := by ext; simp
  map_add' x y := by ext; simp

/-- The restricted quotient map is surjective because `K` was defined as
the full preimage of `L`. -/
theorem claimBIntermediateMap_surjective
    {xs : List A} {n m : ℕ} (P : Theorem21SetPartition xs n m)
    (H : AddSubgroup A) (g : A) :
    Function.Surjective (claimBIntermediateMap P H g) := by
  intro q
  obtain ⟨a, ha⟩ := QuotientAddGroup.mk'_surjective H q.1
  have haK : a ∈ claimBIntermediateSubgroup P H g := by
    change QuotientAddGroup.mk' H a ∈
      claimBIntermediateQuotientSubgroup P H g
    rw [ha]
    exact q.2
  refine ⟨⟨a, haK⟩, ?_⟩
  apply Subtype.ext
  exact ha

/-- The kernel of the restricted quotient map is exactly the internal copy
of `H` inside `K`. -/
theorem claimBIntermediateMap_ker
    {xs : List A} {n m : ℕ} (P : Theorem21SetPartition xs n m)
    (H : AddSubgroup A) (g : A) :
    (claimBIntermediateMap P H g).ker =
      internalAddSubgroup H (claimBIntermediateSubgroup P H g) := by
  ext x
  change claimBIntermediateMap P H g x = 0 ↔ x.1 ∈ H
  constructor
  · intro hx
    have hxq : QuotientAddGroup.mk' H x.1 = 0 :=
      congrArg Subtype.val hx
    have hmem := QuotientAddGroup.eq_iff_sub_mem.mp hxq
    simpa using hmem
  · intro hx
    apply Subtype.ext
    apply QuotientAddGroup.eq_iff_sub_mem.mpr
    simpa using hx

/-- First-isomorphism identification of the internal quotient `K/H` with
the generated quotient subgroup `L`. -/
noncomputable def claimBInternalQuotientEquiv
    {xs : List A} {n m : ℕ} (P : Theorem21SetPartition xs n m)
    (H : AddSubgroup A) (g : A) :
    claimBIntermediateSubgroup P H g ⧸
        internalAddSubgroup H (claimBIntermediateSubgroup P H g) ≃+
      claimBIntermediateQuotientSubgroup P H g :=
  (QuotientAddGroup.quotientAddEquivOfEq
      (claimBIntermediateMap_ker P H g).symm).trans
    (QuotientAddGroup.quotientKerEquivOfSurjective
      (claimBIntermediateMap P H g)
      (claimBIntermediateMap_surjective P H g))

/-- The internal `d*` convolution expressed in the geometrically natural
types `H`, `L`, and `K`. -/
theorem pGroupDStar_H_add_intermediateQuotient_le_intermediate
    {xs : List A} {n m : ℕ} (P : Theorem21SetPartition xs n m)
    (H : AddSubgroup A) (g : A) :
    pGroupDStar H +
        pGroupDStar (claimBIntermediateQuotientSubgroup P H g) ≤
      pGroupDStar (claimBIntermediateSubgroup P H g) := by
  have hconv := pGroupDStar_internal_of_le H
    (claimBIntermediateSubgroup P H g)
    (subgroup_le_claimBIntermediateSubgroup P H g)
  have heq :
      pGroupDStar
          (claimBIntermediateSubgroup P H g ⧸
            internalAddSubgroup H (claimBIntermediateSubgroup P H g)) =
        pGroupDStar (claimBIntermediateQuotientSubgroup P H g) :=
    pGroupDStar_addEquiv (claimBInternalQuotientEquiv P H g)
  simpa only [heq] using hconv

end InternalQuotient

end GaoLean

#print axioms GaoLean.commonCore_subset_addCosetFinset_claimBIntermediateSubgroup
#print axioms GaoLean.claimBIntermediateSubgroup_ne_bot_of_cosetValueSlice_card_two_le
#print axioms GaoLean.closure_claimBCenteredGenerators_eq_top
#print axioms GaoLean.quotientLayer_commonCore_affine_spanning
#print axioms GaoLean.claimBInternalQuotientEquiv
#print axioms GaoLean.pGroupDStar_H_add_intermediateQuotient_le_intermediate
